Repository scramjetorg/transform-hub, pull requests merged in 2022-06, with the labels that each got.

#521 Instance limits + AuditStream limit info
  packages/adapters/src/docker-instance-adapter.ts
  packages/adapters/src/kubernetes-instance-adapter.ts
  packages/adapters/src/process-instance-adapter.ts
  packages/cli/src/lib/commands/sequence.ts
  packages/host/src/lib/auditor.ts
  packages/host/src/lib/csi-controller.ts
  packages/host/src/lib/host.ts
  packages/host/src/lib/middlewares/audit.ts
  packages/obj-logger/src/obj-logger.ts
  packages/types/src/index.ts
  packages/types/src/instance-limits.ts
  packages/types/src/instance-stats.ts
  packages/types/src/lifecycle-adapters.ts
  packages/types/src/lifecycle.ts
  packages/types/src/messages/op-record.ts
  packages/types/src/rest-api-sth/start-sequence.ts
  packages/types/src/runner-config.ts
Labels: high prio, verified

#538 Fix. Pass correct Instance Id to AuditStream on Instance start
  packages/host/src/lib/host.ts
Labels: bug, high prio

#543 End CSIC when instance errored (kill zombies)
  packages/host/src/lib/csi-controller.ts
Labels: verified

#536 Fix for `si seq prune -f`
  packages/adapters/src/dockerode-docker-helper.ts
  packages/api-client/src/instance-client.ts
  packages/cli/src/lib/commands/sequence.ts
  packages/host/src/lib/csi-controller.ts
  packages/host/src/lib/host.ts
  packages/sth-config/src/config-service.ts
  packages/sth/src/bin/hub.ts
  packages/symbols/src/runner-exit-code.ts
  packages/types/src/message-streams.ts
  packages/types/src/messages/kill-sequence.ts
  packages/types/src/sth-command-options.ts
  packages/types/src/sth-configuration.ts
Labels: reviewer-can-merge

#553 Update missing types for kill/stop responses
  packages/host/src/lib/csi-controller.ts
  packages/types/src/rest-api-sth/send-kill-instance.ts
  packages/types/src/rest-api-sth/send-stop-instance.ts
Labels: bug

#564 Eslint fixes
  packages/cli/src/lib/config.ts
  packages/cli/src/utils/stringToBoolean.ts
  packages/host/src/lib/csi-controller.ts
  packages/runner/src/runner.ts
  scripts/dev/sd.ts
Labels: reviewer-can-merge, trivial

#544 CLI Configuration using profiles
  bdd/features/e2e/E2E-010-cli.feature
  bdd/features/e2e/E2E-014-python.feature
  bdd/step-definitions/e2e/cli.ts
  packages/cli/package.json
  packages/cli/src/bin/index.ts
  packages/cli/src/lib/commands/config.ts
  packages/cli/src/lib/commands/hub.ts
  packages/cli/src/lib/commands/index.ts
  packages/cli/src/lib/commands/instance.ts
  packages/cli/src/lib/commands/scope.ts
  packages/cli/src/lib/commands/sequence.ts
  packages/cli/src/lib/commands/space.ts
  packages/cli/src/lib/commands/topic.ts
  packages/cli/src/lib/common.ts
  packages/cli/src/lib/config.ts
  packages/cli/src/lib/errorHandler.ts
  packages/cli/src/lib/output.ts
  packages/cli/src/lib/paths.ts
  packages/cli/src/lib/platform/common.ts
  packages/cli/src/lib/scope.ts
  packages/cli/src/types/index.ts
  packages/cli/src/utils/envs.ts
  packages/cli/src/utils/isDevelopment.ts
  packages/cli/test/cliProcess.ts
  packages/cli/test/config.spec.ts
Labels: enhancement, verified, cli
