Repository scramjetorg/transform-hub, pull requests merged in 2022-11, with the labels that each got.

#732 Show components id, objects in one line
  packages/adapters/src/docker-instance-adapter.ts
  packages/adapters/src/docker-sequence-adapter.ts
  packages/adapters/src/get-instance-adapter.ts
  packages/adapters/src/kubernetes-instance-adapter.ts
  packages/api-server/src/handlers/op.ts
  packages/host/src/lib/csi-controller.ts
  packages/host/src/lib/host.ts
  packages/obj-logger/src/obj-logger.ts
  packages/obj-logger/src/utils/pretty-print.ts
  packages/types/src/component.ts
  packages/types/src/lifecycle-adapters.ts
  packages/types/src/object-logger.ts
Labels: verified

#734 Fix changing profiles
  packages/cli/src/bin/index.ts
  packages/cli/src/lib/commands/config.ts
  packages/cli/src/lib/commands/hub.ts
  packages/cli/src/lib/commands/instance.ts
  packages/cli/src/lib/commands/scope.ts
  packages/cli/src/lib/commands/sequence.ts
  packages/cli/src/lib/commands/space.ts
  packages/cli/src/lib/commands/store.ts
  packages/cli/src/lib/commands/topic.ts
  packages/cli/src/lib/common.ts
  packages/cli/src/lib/config/index.ts
  packages/cli/src/lib/errorHandler.ts
  packages/cli/src/lib/platform/common.ts
Labels: verified, ready to review

#741 [CLI] config & profile tests
  bdd/features/e2e/E2E-012-cli-config.feature
  bdd/step-definitions/e2e/cli.ts
Labels: tests
