Repository scramjetorg/transform-hub, pull requests merged in 2022-07, with the labels that each got.

#587 Fix seq deploy
  packages/cli/src/lib/commands/sequence.ts
Labels: to verify, reviewer-can-merge, cli

#585 [CLI] Small fixes and CLI tests refactor
  bdd/data/sequences/deploy-app/dist/index.js
  bdd/data/sequences/deploy-app/dist/package-lock.json
  bdd/data/sequences/deploy-app/dist/package.json
  bdd/data/sequences/deploy-app/index.ts
  bdd/data/sequences/deploy-app/package-lock.json
  bdd/data/sequences/deploy-app/package.json
  bdd/data/sequences/deploy-app/tsconfig.json
  bdd/features/e2e/E2E-001-samples.feature
  bdd/features/e2e/E2E-010-cli.feature
  bdd/features/e2e/E2E-014-python.feature
  bdd/step-definitions/e2e/cli.ts
  bdd/step-definitions/hub/config.ts
  packages/api-server/src/handlers/get.ts
  packages/cli/src/lib/commands/config.ts
  packages/cli/src/lib/commands/sequence.ts
Labels: ready to merge

#593 Fix description in AppContext
  packages/types/src/app-context.ts
Labels: documentation

#614 Update pull_request_template.md
  .github/pull_request_template.md
Labels: trivial
