Repository scramjetorg/transform-hub, pull requests merged in 2022-05, with the labels that each got.

#475 feat(saferequest) moved request.body.on and abort controller outside …
  bdd/step-definitions/e2e/host-steps.ts
  packages/api-client/src/host-client.ts
  packages/api-client/src/instance-client.ts
  packages/cli/src/lib/commands/instance.ts
  packages/cli/src/lib/commands/topic.ts
  packages/client-utils/src/client-utils.ts
  packages/client-utils/src/types/index.ts
  packages/manager-api-client/src/manager-client.ts
  packages/multi-manager-api-client/src/multi-cpm-client.ts
Labels: verified

#471 Handle async generator in runner-py
  .github/workflows/sth-build-test.yml
  bdd/features/e2e/E2E-014-python.feature
  packages/python-runner/runner.py
  python/reference-apps/python-gen-async/main.py
  python/reference-apps/python-gen-async/package.json
Labels: ready to merge

#479 Settings for cucumber
  .vscode/settings.json
  bdd/README.md
  bdd/delay.test.result.txt
Labels: trivial, ready to merge

#299 Python api-client implementation
  .github/workflows/sth-build-test.yml
  package.json
  packages/api-client-py/README.md
  packages/api-client-py/client/__init__.py
  packages/api-client-py/client/host_client.py
  packages/api-client-py/client/instance_client.py
  packages/api-client-py/client/sequence_client.py
  packages/api-client-py/features/environment.py
  packages/api-client-py/features/host.feature
  packages/api-client-py/features/sequence.feature
  packages/api-client-py/features/steps/host.py
  packages/api-client-py/features/steps/world.py
  packages/api-client-py/package.json
  packages/api-client-py/requirements-dev.txt
  packages/api-client-py/requirements.txt
  packages/api-client-py/setup.py
Labels: enhancement, ready to merge

#489 CPM URL and ID must be provided together
  packages/host/src/lib/host.ts
  packages/types/src/error-codes/host-error.ts
Labels: verified

#490 CLI: Do not display a stream response when sending input to the Instance
  packages/cli/src/lib/commands/instance.ts
Labels: verified

#491 Handle Runner failure and Sequence errors on Sequence start
  package.json
  packages/api-client/src/sequence-client.ts
  packages/cli/src/lib/commands/sequence.ts
  packages/cli/src/lib/output.ts
  packages/host/src/lib/csi-controller.ts
  packages/host/src/lib/host.ts
  packages/runner/src/runner.ts
  packages/symbols/src/runner-exit-code.ts
Labels: verified

#492 Runner pod - support resource limits
  packages/adapters/src/kubernetes-config-decoder.ts
  packages/adapters/src/kubernetes-instance-adapter.ts
  packages/sth/src/bin/hub.ts
  packages/types/src/sth-command-options.ts
  packages/types/src/sth-configuration.ts
Labels: to verify

#493 [SCP-3733] Hide only the not implemented features
  packages/cli/package.json
  packages/cli/src/bin/index.ts
  packages/cli/src/lib/commands/completion.ts
  packages/cli/src/lib/commands/config.ts
  packages/cli/src/lib/commands/hub.ts
  packages/cli/src/lib/commands/index.ts
  packages/cli/src/lib/commands/init.ts
  packages/cli/src/lib/commands/instance.ts
  packages/cli/src/lib/commands/scope.ts
  packages/cli/src/lib/commands/sequence.ts
  packages/cli/src/lib/commands/space.ts
  packages/cli/src/lib/commands/topic.ts
  packages/cli/src/lib/commands/util.ts
Labels: verified, to verify

#506 [CLIfix] `si hub ls` does not return output in json format
  packages/cli/src/lib/commands/config.ts
  packages/cli/src/lib/commands/hub.ts
  packages/cli/src/lib/commands/sequence.ts
  packages/cli/src/lib/commands/space.ts
Labels: verified

#502 Log pretty error when pods quotas are reached
  packages/adapters/src/kubernetes-client-adapter.ts
  packages/adapters/src/kubernetes-instance-adapter.ts
Labels: verified

#499 [SCP-3783] Revive CLI log test
  bdd/features/e2e/E2E-010-cli.feature
  bdd/step-definitions/e2e/cli.ts
Labels: reviewer-can-merge, ready to merge

#508 [Beta] Default hub and space display
  packages/cli/src/lib/commands/hub.ts
Labels: in progress

#522 Fix build script so that it works with non-js, asset only packages
  package.json
  packages/adapters/package.json
  packages/pre-runner/Dockerfile
  packages/pre-runner/package.json
  packages/python-runner/package.json
  packages/sth/Dockerfile
  scripts/build-all.js
  scripts/lib/build-utils.js
  scripts/lib/pre-pack.js
Labels: reviewer-can-merge, trivial

#517 Count rx/tx without use socket.bytesRead/Writen
  packages/host/src/lib/auditor.ts
  packages/host/src/lib/middlewares/audit.ts
Labels: high prio
