Repository scramjetorg/transform-hub, pull requests merged in 2022-10, with the labels that each got.

#708 Show sequence upload progress in CLI with --progress flag
  packages/cli/src/bin/index.ts
  packages/cli/src/lib/commands/sequence.ts
  packages/cli/src/lib/helpers/sequence.ts
Labels: verified, reviewer-can-merge, ready to merge

#713 (helm) sth support configMap
  docs/guides/kubernetes/charts/templates/sth-config.yaml
  docs/guides/kubernetes/charts/templates/sth-statefulset.yaml
  docs/guides/kubernetes/charts/values.yaml
Labels: verified

#628 instance/inout endpoint
  docs/adapters/classes/KubernetesInstanceAdapter.md
  docs/api-client/README.md
  docs/host/classes/CSIController.md
  docs/symbols/enums/RunnerExitCode.md
  docs/types/modules.md
  packages/api-client/README.md
  packages/api-client/src/readme.mtpl
  packages/host/src/lib/csi-controller.ts
  packages/telemetry/README.md
Labels: enhancement, PoC

#714 (helm) liveness & readiness probe, fix port mapping
  docs/guides/kubernetes/charts/Chart.yaml
  docs/guides/kubernetes/charts/templates/sth-statefulset.yaml
  docs/guides/kubernetes/charts/values.yaml
Labels: verified

#718 Fix/eslintup
  package.json
  packages/adapters/src/kubernetes-client-adapter.ts
  packages/adapters/src/kubernetes-instance-adapter.ts
  packages/adapters/src/kubernetes-sequence-adapter.ts
  packages/cli/src/lib/config/profileManager.ts
  packages/cli/src/lib/config/siConfig.ts
  packages/cli/src/types/commander-completion.d.ts
  packages/host/src/lib/host.ts
  packages/host/src/lib/sd-adapter.ts
  packages/host/src/lib/socket-server.ts
  packages/obj-logger/src/obj-logger.ts
  packages/runner/src/mock/runner.ts
  yarn.lock
Labels: to verify

#717 Reject topic upstream request with conflicting content-type
  packages/host/src/lib/sd-adapter.ts
Labels: verified

#648 Get sequence from SequenceStore if not found locally
  package.json
  packages/adapters/src/index.ts
  packages/host/package.json
  packages/host/src/lib/cpm-connector.ts
  packages/host/src/lib/host.ts
  packages/host/src/lib/s3-client.ts
  packages/types/src/manager-configuration.ts
  packages/verser/src/lib/verser-client.ts
  packages/verser/src/lib/verser-connection.ts
  yarn.lock
Labels: enhancement
