Repository scramjetorg/transform-hub, pull requests merged in 2022-04, with the labels that each got.

#364 commands update
  .github/workflows/release-test.yml
  .github/workflows/sth-build-test.yml
  bdd/data/sample-log.log.ansi
  bdd/data/sample-log.log.plain
  bdd/data/sample-log.log.source
  bdd/features/e2e/E2E-010-cli.feature
  bdd/features/e2e/E2E-014-python.feature
  bdd/step-definitions/e2e/cli.ts
  package.json
  packages/cli/package.json
  packages/cli/src/bin/index.ts
  packages/cli/src/index.ts
  packages/cli/src/lib/commands/auth.ts
  packages/cli/src/lib/commands/completion.ts
  packages/cli/src/lib/commands/config.ts
  packages/cli/src/lib/commands/host.ts
  packages/cli/src/lib/commands/hub.ts
  packages/cli/src/lib/commands/index.ts
  packages/cli/src/lib/commands/init.ts
  packages/cli/src/lib/commands/instance.ts
  packages/cli/src/lib/commands/pack.ts
  packages/cli/src/lib/commands/scope.ts
  packages/cli/src/lib/commands/sequence.ts
  packages/cli/src/lib/commands/space.ts
  packages/cli/src/lib/commands/topic.ts
  packages/cli/src/lib/commands/util.ts
  packages/cli/src/lib/common.ts
  packages/cli/src/lib/config.ts
  packages/cli/src/lib/output.ts
  packages/cli/src/lib/paths.ts
  packages/cli/src/lib/platform/common.ts
  packages/cli/src/types/index.ts
  packages/cli/src/utils/isDevelopment.ts
  packages/cli/src/utils/stringToBoolean.ts
Labels: enhancement, verified

#403 setPlatformDefaults stuck on invalid middlewareApiUrl fix
  packages/cli/src/lib/platform/common.ts
Labels: verified

#405 Image choice for Kubernates adapter
  packages/adapters/src/kubernetes-config-decoder.ts
  packages/adapters/src/kubernetes-instance-adapter.ts
  packages/python-runner/Dockerfile
  packages/python-runner/unpack.sh
  packages/python-runner/wait-for-sequence-and-start.sh
  packages/sth-config/src/config-service.ts
  packages/sth/src/bin/hub.ts
  packages/types/src/sth-command-options.ts
  packages/types/src/sth-configuration.ts
Labels: verified

#362 feat(up-docs-0-19) Update CLI and API doc.
  README.md
  packages/cli/README.md
  packages/cli/src/readme.mtpl
Labels: verified

#407 A timings refapp
  packages/reference-apps/timings-test/.eslintrc.js
  packages/reference-apps/timings-test/index.ts
  packages/reference-apps/timings-test/package.json
  packages/reference-apps/timings-test/tsconfig.json
Labels: trivial

#419 Bugfix for CLI --help
  packages/cli/src/lib/commands/config.ts
  packages/cli/src/lib/commands/hub.ts
  packages/cli/src/lib/commands/init.ts
  packages/cli/src/lib/commands/instance.ts
  packages/cli/src/lib/commands/scope.ts
  packages/cli/src/lib/commands/sequence.ts
  packages/cli/src/lib/commands/space.ts
  packages/cli/src/lib/commands/topic.ts
Labels: verified

#425 Introduce: si seq prune
  packages/cli/README.md
  packages/cli/src/lib/commands/sequence.ts
  packages/cli/src/lib/config.ts
  packages/cli/src/lib/output.ts
  packages/cli/src/readme.mtpl
  packages/types/src/rest-api-sth/get-sequence.ts
Labels: verified

#454 Select first healthy hub as default in CLI
  packages/cli/src/lib/platform/common.ts
Labels: verified

#456 Fix for @scramjet/constants' package.json
  packages/constants/package.json
Labels: reviewer-can-merge

#455 [Bugfix] Parse seq args in CLI "si seq deploy"
  bdd/features/e2e/E2E-010-cli.feature
  bdd/step-definitions/e2e/cli.ts
  packages/cli/src/lib/commands/sequence.ts
Labels: reviewer-can-merge

#239 IaC startup mode
  bdd/data/sample-config-exit.json
  bdd/data/sample-config-output.txt
  bdd/data/sample-config.json
  bdd/data/sequences/args-config-test/LICENSE
  bdd/data/sequences/args-config-test/index.d.ts
  bdd/data/sequences/args-config-test/index.js
  bdd/data/sequences/args-config-test/index.js.map
  bdd/data/sequences/args-config-test/package-lock.json
  bdd/data/sequences/args-config-test/package.json
  bdd/features/e2e/E2E-010-cli.feature
  bdd/features/e2e/hub/HUB-001-host-config.feature
  bdd/features/e2e/hub/HUB-002-host-iac.feature
  bdd/iac-test-data/sequences/hello-1/index.js
  bdd/iac-test-data/sequences/hello-1/package.json
  bdd/iac-test-data/sequences/hello-2/index.js
  bdd/iac-test-data/sequences/hello-2/package.json
  bdd/iac-test-data/start-config.json
  bdd/lib/host-utils.ts
  bdd/step-definitions/e2e/cli.ts
  bdd/step-definitions/hub/config.ts
  bdd/step-definitions/world.ts
  packages/adapters/src/kubernetes-sequence-adapter.ts
  packages/adapters/src/process-sequence-adapter.ts
  packages/host/src/lib/host.ts
  packages/host/src/lib/start-host.ts
  packages/reference-apps/args-config-test/.eslintrc.js
  packages/reference-apps/args-config-test/index.ts
  packages/reference-apps/args-config-test/package.json
  packages/reference-apps/args-config-test/tsconfig.json
  packages/runner/src/runner-app-context.ts
  packages/runner/src/runner.ts
  packages/sth-config/src/config-service.ts
  packages/sth/package.json
  packages/sth/src/bin/hub.ts
  packages/sth/src/index.ts
  packages/types/src/app-context.ts
  packages/types/src/dto/index.ts
  packages/types/src/dto/start-sequence.ts
  packages/types/src/error-codes/host-error.ts
  packages/types/src/index.ts
  packages/types/src/sequence-adapter.ts
  packages/types/src/sth-command-options.ts
  packages/types/src/sth-configuration.ts
  packages/utility/src/defer.ts
  packages/utility/src/index.ts
  packages/utility/src/read-config-file.ts
  packages/utility/src/typeguards/dto/sequence-start.ts
  packages/utility/src/typeguards/index.ts
Labels: verified

#459 Topic tests run on the same STH
  bdd/features/e2e/E2E-010-cli.feature
  bdd/features/e2e/E2E-013-topic.feature
  bdd/step-definitions/e2e/cli.ts
  bdd/step-definitions/e2e/host-steps.ts
  package.json
  packages/api-client/src/sequence-client.ts
Labels: reviewer-can-merge

#470 Align package version
  packages/reference-apps/args-config-test/package.json
  packages/reference-apps/timings-test/package.json
  yarn.lock
Labels: bug, reviewer-can-merge, trivial

#476 [SCP-3670] Add getInstances and getSequences methods to ManagerClient.
  packages/manager-api-client/src/manager-client.ts
Labels: verified
