Repository scramjetorg/transform-hub, pull requests merged in 2022-09, with the labels that each got.

#664 si seq send <dir>
  packages/cli/src/lib/commands/sequence.ts
Labels: verified

#669 [CLI] fix-reset all not clearing session
  packages/cli/src/lib/commands/config.ts
Labels: cli

#625 Validate topic name
  packages/cli/src/lib/commands/topic.ts
Labels: verified

#666 Unpipe input from topic when instance is terminated
  bdd/step-definitions/e2e/cli.ts
  packages/host/src/lib/csi-controller.ts
  packages/host/src/lib/host.ts
Labels: do not merge

#665 [CLI] fix returned exit codes
  bdd/features/e2e/E2E-010-cli.feature
  bdd/step-definitions/e2e/cli.ts
  package-lock.json
  packages/cli/src/lib/commands/completion.ts
  packages/cli/src/lib/commands/config.ts
  packages/cli/src/lib/commands/hub.ts
  packages/cli/src/lib/commands/instance.ts
  packages/cli/src/lib/commands/scope.ts
  packages/cli/src/lib/commands/sequence.ts
  packages/cli/src/lib/commands/space.ts
  packages/cli/src/lib/common.ts
  packages/cli/src/lib/config.ts
  packages/cli/src/lib/errorHandler.ts
  packages/cli/src/lib/helpers/instance.ts
  packages/cli/src/lib/helpers/scope.ts
  packages/cli/src/lib/helpers/sequence.ts
  packages/cli/src/lib/output.ts
Labels: verified, cli

#673 [STH] Instance stop and kill body params fix
  packages/api-client/src/instance-client.ts
  packages/host/src/lib/csi-controller.ts
  packages/types/src/instance.ts
  packages/types/src/messages/index.ts
Labels: cli, ready to review, API

#679 Allow to merge if target key not exists
  packages/utility/src/merge.ts
Labels: trivial, ready to review

#682 Fix telemtry sizes and environment
  docs/adapters/classes/DockerSequenceAdapter.md
  docs/adapters/classes/KubernetesSequenceAdapter.md
  docs/api-client/README.md
  docs/api-client/classes/ClientError.md
  docs/api-client/classes/ClientUtils.md
  docs/api-client/classes/InstanceClient.md
  docs/api-client/interfaces/ClientProvider.md
  docs/api-client/interfaces/HttpClient.md
  docs/api-client/modules.md
  docs/host/classes/CSIController.md
  docs/host/classes/Host.md
  docs/sth-config/classes/ConfigService.md
  docs/sth-config/modules.md
  docs/telemetry/.nojekyll
  docs/telemetry/README.md
  docs/telemetry/modules.md
  docs/types/enums/InstanceStatus.md
  docs/types/modules.md
  docs/types/modules/MRestAPI.md
  docs/types/modules/STHRestAPI.md
  packages/host/src/lib/host.ts
  packages/sth-config/src/config-service.ts
  packages/sth/src/bin/hub.ts
  packages/telemetry/src/adapters/loki.ts
  packages/types/src/sth-command-options.ts
  packages/types/src/telemetry-config.ts
Labels: verified

#675 Instruction fixes
  README.md
  images/node&npm_version.png
Labels: do not merge, trivial

#697 [CLI] fix loading of broken profile files
  packages/cli/src/lib/commands/config.ts
  packages/cli/src/lib/config.ts
  packages/cli/src/lib/config/config.ts
  packages/cli/src/lib/config/defaultFileConfig.ts
  packages/cli/src/lib/config/fileConfig.ts
  packages/cli/src/lib/config/index.ts
  packages/cli/src/lib/config/profileConfig.ts
  packages/cli/src/lib/config/profileManager.ts
  packages/cli/src/lib/config/sessionConfig.ts
  packages/cli/src/lib/config/siConfig.ts
  packages/cli/src/lib/errorHandler.ts
  packages/cli/src/lib/paths.ts
Labels: cli, ready to review

#698 Add version to telemetry
  packages/adapters/src/utils.ts
  packages/host/src/lib/csi-controller.ts
  packages/host/src/lib/host.ts
Labels: verified

#700 Add args field to instance, change sequenceArgs to args in sequences
  packages/adapters/src/docker-sequence-adapter.ts
  packages/adapters/src/kubernetes-sequence-adapter.ts
  packages/adapters/src/process-sequence-adapter.ts
  packages/adapters/src/validate-sequence-package-json.ts
  packages/cli/src/lib/commands/sequence.ts
  packages/cli/src/lib/helpers/sequence.ts
  packages/host/src/lib/csi-controller.ts
  packages/host/src/lib/host.ts
  packages/pre-runner/identify.sh
  packages/types/src/instance-store.ts
  packages/types/src/runner-config.ts
  packages/types/src/sequence-package-json.ts
Labels: verified

#684 [SHN-854] add nodejs 18.x LTS
  .github/workflows/_main_sth-build-test-node-18.yml
Labels: in progress

#704 Check k8s quota before instance start
  docs/guides/kubernetes/charts/Chart.yaml
  docs/guides/kubernetes/charts/templates/sth-role.yaml
  docs/guides/kubernetes/manifests/sth-rbac.yaml
  packages/adapters/src/kubernetes-client-adapter.ts
  packages/adapters/src/kubernetes-config-decoder.ts
  packages/adapters/src/kubernetes-instance-adapter.ts
  packages/host/src/lib/csi-controller.ts
  packages/sth/src/bin/hub.ts
  packages/symbols/src/runner-exit-code.ts
  packages/types/src/sth-command-options.ts
  packages/types/src/sth-configuration.ts
Labels: verified, kubernetes
