Repository scramjetorg/transform-hub, pull requests merged in 2022-08, with the labels that each got.

#600 [CLI] Add session config display command
  packages/cli/src/lib/commands/config.ts
Labels: verified

#615 Remove stream object from topics response
  packages/host/src/lib/sd-adapter.ts
Labels: trivial

#621 Fix delete Sequence with running Instances
  packages/host/src/lib/host.ts
Labels: verified

#622 Change Stopped / Killed instance status to `completed`, provide exit info
  packages/host/src/lib/csi-controller.ts
  packages/runner/src/runner.ts
  packages/symbols/src/runner-exit-code.ts
  packages/types/src/instance-store.ts
Labels: verified

#626 Allow to send event without payload
  bdd/features/e2e/E2E-010-cli.feature
  packages/host/src/lib/csi-controller.ts
  packages/model/src/get-message.ts
  packages/runner/src/runner-app-context.ts
Labels: verified

#627 Use correct hub in tests
  .github/workflows/test-bdd-process.yml
  bdd/features/hub/HUB-001-host-config.feature
  bdd/step-definitions/e2e/host-steps.ts
  bdd/step-definitions/hub/config.ts
Labels: to verify

#633 [CLI] Add session id display
  packages/cli/src/lib/config.ts
  packages/cli/src/types/index.ts
Labels: trivial

#646 CLI clean session config on profile change
  packages/cli/src/lib/commands/config.ts
  packages/cli/src/lib/config.ts
Labels: cli, ready to merge

#641 Add --no-colors flag
  packages/host/src/lib/host.ts
  packages/obj-logger/src/utils/pretty-print.ts
  packages/sth-config/src/config-service.ts
  packages/sth/src/bin/hub.ts
  packages/types/src/sth-command-options.ts
  packages/utility/src/merge.ts
Labels: verified

#647 sth add error msg on invalid instace id
  packages/host/src/lib/host.ts
Labels: ready to review

#643 Support x-name header on sequence post|put
  packages/adapters/src/docker-sequence-adapter.ts
  packages/adapters/src/kubernetes-sequence-adapter.ts
  packages/adapters/src/process-sequence-adapter.ts
  packages/api-client/src/host-client.ts
  packages/api-client/src/sequence-client.ts
  packages/api-server/src/handlers/op.ts
  packages/api-server/src/handlers/stream.ts
  packages/api-server/src/index.ts
  packages/cli/src/lib/commands/sequence.ts
  packages/client-utils/src/client-utils.ts
  packages/client-utils/src/types/index.ts
  packages/host/src/lib/csi-controller.ts
  packages/host/src/lib/host.ts
  packages/types/src/api-expose.ts
  packages/types/src/op-response.ts
  packages/types/src/rest-api-sth/get-instance.ts
  packages/types/src/rest-api-sth/get-sequence.ts
  packages/types/src/sequence-adapter.ts
Labels: verified

#650 STH add missing sequence info
  packages/adapters/src/docker-sequence-adapter.ts
  packages/adapters/src/kubernetes-sequence-adapter.ts
  packages/adapters/src/process-sequence-adapter.ts
  packages/adapters/src/validate-sequence-package-json.ts
  packages/types/src/runner-config.ts
  packages/types/src/sequence-package-json.ts
Labels: ready to review

#617 Rewrite STH-SCP connection
  packages/api-client/src/host-client.ts
  packages/host/src/lib/cpm-connector.ts
  packages/host/src/lib/host.ts
  packages/types/src/rest-api-sth/get-status.ts
  packages/types/src/rest-api-sth/index.ts
  packages/verser/src/lib/verser-client.ts
  packages/verser/src/lib/verser-connection.ts
Labels: verified

#636 Add missing commands to the start snippet
  packages/sth/README.md
  packages/sth/src/readme.mtpl
Labels: bug, high prio, ready to review

#653 [STH] Add missing repository field to /sequences
  packages/adapters/src/docker-sequence-adapter.ts
  packages/adapters/src/kubernetes-sequence-adapter.ts
  packages/adapters/src/process-sequence-adapter.ts
  packages/adapters/src/validate-sequence-package-json.ts
  packages/pre-runner/identify.sh
  packages/types/src/runner-config.ts
  packages/types/src/sequence-package-json.ts
Labels: verified

#654 [CLI] display object depth null
  packages/cli/src/lib/output.ts
Labels: verified, ready to review

#659 [CLI] Fix broken prod_env check
  packages/cli/src/lib/commands/index.ts
  packages/cli/src/lib/commands/scope.ts
  packages/cli/src/lib/commands/space.ts
Labels: cli

#658 [STH] Unify error responses
  packages/api-client/src/sequence-client.ts
  packages/api-server/src/handlers/get.ts
  packages/api-server/src/handlers/op.ts
  packages/host/src/lib/csi-controller.ts
  packages/host/src/lib/host.ts
  packages/types/src/load-check-stat.ts
  packages/types/src/op-response.ts
  packages/types/src/rest-api-manager/common.ts
  packages/types/src/rest-api-sth/get-sequence-instances.ts
  packages/types/src/rest-api-sth/start-sequence.ts
  scripts/build-all.js
  scripts/run-script.js
Labels: verified, ready to review, API

#655 Disable Nagle in Runner connections
  packages/runner/src/host-client.ts
Labels: verified, reviewer-can-merge, ready to review
