Repository scramjetorg/transform-hub, pull requests merged in 2022-02, with the labels that each got.

#248 Fixes #243
  packages/adapters/src/docker-sequence-adapter.ts
  packages/sth/src/bin/hub.ts
Labels: verified

#257 Corrected Discord link to one that won't expire.
  conf/readme-parts/shields.md
  packages/api-client/README.md
  packages/cli/README.md
  packages/sth/README.md
Labels: documentation, verified, fix to be released, trivial

#270 Add classes to make look API doc fancy and make some fixes.
  packages/api-client/README.md
Labels: documentation

#265 Python runner BDD tests
  bdd/README.md
  bdd/features/e2e/E2E-014-python.feature
  bdd/step-definitions/e2e/host-steps.ts
  packages/adapters/src/process-instance-adapter.ts
  python/reference-apps/chunk-lengths/chunk-lengths.py
  python/reference-apps/chunk-lengths/package.json
  python/reference-apps/chunk-lengths/scramjet
  python/reference-apps/python-debug-args/args.py
  python/reference-apps/python-debug-args/package.json
  python/reference-apps/python-debug-args/scramjet
  python/reference-apps/python-exception-test/exception.py
  python/reference-apps/python-exception-test/package.json
  python/reference-apps/python-forever/forever.py
  python/reference-apps/python-forever/package.json
  python/reference-apps/python-hello/hello.py
  python/reference-apps/python-hello/package.json
  python/reference-apps/python-hello/scramjet
  python/reference-apps/python-stdinout/package.json
  python/reference-apps/python-stdinout/scramjet
  python/reference-apps/python-stdinout/stdinout.py
  python/reference-apps/python-stop-handler/package.json
  python/reference-apps/python-stop-handler/stop-handler.py
  python/reference-apps/unhealthy-sequence/package.json
  python/reference-apps/unhealthy-sequence/unhealthy.py
  python/runner/runner.py
  python/test/sample_unicode_1.txt
Labels: verified

#247 feat: Kubernetes Runtime Adapters
  ENV_VARS.md
  README.md
  bdd/features/e2e/E2E-010-cli.feature
  bdd/lib/host-utils.ts
  bdd/step-definitions/e2e/host-steps.ts
  package.json
  packages/adapters/package.json
  packages/adapters/src/get-instance-adapter.ts
  packages/adapters/src/get-sequence-adapter.ts
  packages/adapters/src/index.ts
  packages/adapters/src/kubernetes-client-adapter.ts
  packages/adapters/src/kubernetes-config-decoder.ts
  packages/adapters/src/kubernetes-instance-adapter.ts
  packages/adapters/src/kubernetes-sequence-adapter.ts
  packages/host/src/lib/csi-controller.ts
  packages/host/src/lib/host.ts
  packages/obj-logger/src/utils/pretty-print.ts
  packages/pre-runner/Dockerfile
  packages/runner/Dockerfile
  packages/runner/src/runner.ts
  packages/runner/unpack.sh
  packages/runner/wait-for-sequence-and-start.sh
  packages/sth-config/src/config-service.ts
  packages/sth/src/bin/hub.ts
  packages/types/src/csi-config.ts
  packages/types/src/index.ts
  packages/types/src/messages/monitoring.ts
  packages/types/src/runner-config.ts
  packages/types/src/sth-configuration.ts
  yarn.lock
Labels: verified

#283 Avoid mutally exclusive runtime adapters options
  packages/sth/src/bin/hub.ts
Labels: verified

#285 Faster refapps building.
  .github/workflows/release-test.yml
  .github/workflows/sth-build-test.yml
  README.md
  bdd/README.md
  package.json
  packages/reference-apps/avengers-names-output/package.json
  packages/reference-apps/big-file-sequence/package.json
  packages/reference-apps/can-keep-alive/package.json
  packages/reference-apps/checksum-sequence/package.json
  packages/reference-apps/csv-transform/index.ts
  packages/reference-apps/csv-transform/package.json
  packages/reference-apps/delay-out-in-a/package.json
  packages/reference-apps/delay-out-in-b/package.json
  packages/reference-apps/durability-preservation-event/README.md
  packages/reference-apps/durability-preservation-event/package.json
  packages/reference-apps/durability-preservation-tcp/README.md
  packages/reference-apps/durability-preservation-tcp/package.json
  packages/reference-apps/durability-preservation/README.md
  packages/reference-apps/durability-preservation/package.json
  packages/reference-apps/endless-names-output/package.json
  packages/reference-apps/event-sequence copy/tsconfig.json
  packages/reference-apps/event-sequence-2/package.json
  packages/reference-apps/event-sequence-v2/package.json
  packages/reference-apps/event-sequence/package.json
  packages/reference-apps/flood-stdout-sequence/package.json
  packages/reference-apps/healthy-sequence/package.json
  packages/reference-apps/hello-alice-out/package.json
  packages/reference-apps/hello-hulk-out/package.json
  packages/reference-apps/hello-input-out/package.json
  packages/reference-apps/inert-function-js/package.json
  packages/reference-apps/inert-function/package.json
  packages/reference-apps/inert-sequence-1/package.json
  packages/reference-apps/inert-sequence-2-with-delay/package.json
  packages/reference-apps/inert-sequence-2/package.json
  packages/reference-apps/inert-sequence-3/package.json
  packages/reference-apps/multi-outputs/package.json
  packages/reference-apps/output-streams/package.json
  packages/reference-apps/ports-sequence/package.json
  packages/reference-apps/read-function/package.json
  packages/reference-apps/read-sequence-1/package.json
  packages/reference-apps/read-sequence-2/package.json
  packages/reference-apps/read-sequence-3/package.json
  packages/reference-apps/sequence-20s-kill-handler/package.json
  packages/reference-apps/sequence-20s/package.json
  packages/reference-apps/sequence-with-error/package.json
  packages/reference-apps/stdio-sequence/package.json
  packages/reference-apps/transform-function/package.json
  packages/reference-apps/transform-sequence-1/package.json
  packages/reference-apps/transform-sequence-2/package.json
  packages/reference-apps/transform-sequence-3/package.json
  packages/reference-apps/unhealthy-sequence/package.json
  packages/reference-apps/write-function/package.json
  packages/reference-apps/write-sequence-1/package.json
  packages/reference-apps/write-sequence-2/package.json
  packages/reference-apps/write-sequence-3/package.json
  yarn.lock
Labels: trivial

#269 Support for topics in Python Runner
  bdd/README.md
  bdd/features/e2e/E2E-014-python.feature
  python/reference-apps/python-topic-consumer/main.py
  python/reference-apps/python-topic-consumer/package.json
  python/reference-apps/python-topic-producer/main.py
  python/reference-apps/python-topic-producer/package.json
  python/runner/runner.py
Labels: verified

#288 Docker support for python runner
  bdd/features/e2e/hub/HUB-001-host-config.feature
  bdd/step-definitions/hub/config.ts
  packages/adapters/src/docker-sequence-adapter.ts
  packages/adapters/src/process-instance-adapter.ts
  packages/reference-apps/hello-alice-out/package.json
  packages/reference-apps/hello-hulk-out/package.json
  packages/reference-apps/hello-input-out/package.json
  packages/runner/src/bin/start-runner.ts
  packages/sth-config/src/config-service.ts
  packages/sth-config/src/image-config.json
  packages/sth-config/test/index.spec.ts
  packages/types/src/sth-configuration.ts
  python/runner/Dockerfile
  python/runner/docker-entrypoint.sh
  python/runner/logging_setup.py
  python/runner/package.json
  python/runner/runner.py
Labels: verified
