Repository scramjetorg/transform-hub, pull requests merged in 2023-08, with the labels that each got.

#923 Feat/remove config logs
  packages/host/src/lib/host.ts
Labels: verified, ready to review

#926 Changes in types and messages
  bdd/step-definitions/hub/config.ts
  packages/cli/src/lib/helpers/instance.ts
  packages/host/src/lib/cpm-connector.ts
  packages/host/src/lib/csi-controller.ts
  packages/host/src/lib/host.ts
  packages/types/src/instance-store.ts
  packages/types/src/instance.ts
  packages/types/src/messages/instance.ts
  packages/types/src/rest-api-manager/common.ts
  packages/types/src/rest-api-manager/get-entities.ts
  packages/types/src/rest-api-manager/get-instance.ts
  packages/types/src/rest-api-manager/get-instances.ts
  packages/types/src/rest-api-manager/get-list.ts
  packages/types/src/rest-api-manager/get-sequence-ids.ts
  packages/types/src/rest-api-manager/get-topics.ts
  packages/types/src/rest-api-manager/index.ts
  packages/types/src/rest-api-sth/get-instance.ts
  packages/types/src/runner-config.ts
  packages/types/src/sequence-adapter.ts
  packages/types/src/sequence-package-json.ts
Labels: do not merge

#930 Fix CLI not to read space state when it's not needed
  packages/cli/src/bin/index.ts
  packages/cli/src/lib/commands/hub.ts
  packages/cli/src/lib/commands/instance.ts
  packages/cli/src/lib/commands/sequence.ts
  packages/cli/src/lib/commands/space.ts
  packages/cli/src/lib/commands/store.ts
  packages/cli/src/lib/commands/topic.ts
  packages/cli/src/lib/platform/common.ts
Labels: reviewer-can-merge, ready to review

#927 Delete hub in Client/CLI
  packages/cli/src/lib/commands/hub.ts
  packages/cli/src/lib/commands/space.ts
  packages/cli/src/lib/helpers/various.ts
  packages/manager-api-client/src/manager-client.ts
  packages/types/src/rest-api-manager/delete-hub.ts
  packages/types/src/rest-api-manager/index.ts
Labels: verified, cli, API

#932 fix/topic streaming bug
  .gitignore
  bdd/features/e2e/E2E-011-cli-topic.feature
  bdd/features/e2e/E2E-013-topic.feature
  bdd/lib/utils.ts
  bdd/step-definitions/e2e/cli.ts
  bdd/step-definitions/e2e/expectedResponses.ts
  bdd/step-definitions/e2e/host-steps.ts
  bdd/step-definitions/world.ts
  packages/api-client/src/host-client.ts
  packages/api-server/src/handlers/stream.ts
  packages/api-server/src/index.ts
  packages/api-server/src/lib/data-extractors.ts
  packages/api-server/src/lib/definitions.ts
  packages/api-server/test/pause-resume.ts
  packages/api-server/test/stream-methods.spec.ts
  packages/cli/src/lib/commands/topic.ts
  packages/client-utils/package.json
  packages/client-utils/src/client-utils.ts
  packages/client-utils/src/types/index.ts
  packages/host/src/lib/auditor.ts
  packages/host/src/lib/host.ts
  packages/host/src/lib/middlewares/audit.ts
  packages/host/src/lib/serviceDiscovery/sd-adapter.ts
  packages/host/src/lib/serviceDiscovery/topic.ts
  packages/host/src/lib/serviceDiscovery/topicRouter.ts
  packages/sth-config/src/index.ts
  packages/types/src/api-expose.ts
  yarn.lock
Labels: verified
